name: Create a PR from actions
on: 
    workflow_dispatch:

jobs:
    main_job:
        runs-on: ubuntu-latest
        steps:
          - name: Generate a token
            id: gen_token
            uses: actions/create-github-app-token@v1
            with:
                app-id: ${{ secrets.PR_APP_ID }}
                private-key: ${{ secrets.PR_APP_KEY }}
                owner: ${{ github.repository_owner }}
          
          - name: Checkout the source
            uses: actions/checkout@v4
            with:
                token: ${{ steps.gen_token.outputs.token }}
                path: repo

          - name: Update some files
            id: add-content
            run: |
                date >> ./repo/current_time.txt

          #copied from substrate-connect
          - uses: peter-evans/create-pull-request@v6
            id: create-pr
            with:
                token: ${{ steps.gen_token.outputs.token }}
                committer: CICD team <cicd-team@parity.io>
                author: CICD team <cicd-team@parity.io>
                path: repo
                branch: automatic-checkpoints-update
                base: master
                title: "chore: update checkpoints in chain specifications"
                body: >
                    This pull request has been automatically generated by downloading chain
                    specifications from various JSON-RPC endpoints and extracting their checkpoints.

                    Keep in mind that introducing a malicious checkpoint can redirect users to the wrong
                    chain. If this pull request looks suspicious, please be cautious.
                    labels: "automerge"
                    commit-message: "chore: update checkpoints in chain specifications"
                    delete-branch: true
